[phases.setup]
nixPkgs = ["python311", "ghostscript"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn resize_images_ui:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2"
